:e f	edit file f, unless changes have been made
:e! f	edit file f always (by default reload current)
:wn :wN	write file and edit next, previous one
:n :N	edit next, previous file in list
:rw	write range r to current file
:rw f	write range r to file f
:rw>>f	append range r to file f
:q :q!	quit and conï¬rm, quit and discard changes
:wq or :x or ZZ	write to current file and exit
<up> <down>	recall commands starting with current
:r 
